[package]
name = "spectro"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
convolutions-rs = "0.3.4"
csv = "1.3.1"
hound = "3.5.1"
interp = "2.0.2"
ndarray = "0.15.3"
serde = { version = "1.0.219", features = ["derive"] }
smartcore = { version = "0.4.0", features = ["serde"] }
spectrum-analyzer = "1.6.0"
